### PR TITLE
API usability issues

### PR DESCRIPTION
**Pull request by cciccia**
I'll admit i had no idea where to put the 403 test; it's not specific to that view.  feel free to move it.

### CODE REVIEW

**Comment by ConnorJC3** [comment]
Oh, thanks. I didn't realize I forgot to rescue from access denied. Let me move the test real quick before I merge this in.

**Comment by ConnorJC3** [comment]
@cciccia Are you sending the correct `Accept` header and appending `.json` to your requests? That should always accept/send JSON.

**Comment by cciccia** [comment]
im not doing the latter, thats probably it. Thanks.

**Comment by ConnorJC3** [comment]
Yeah, if possible do that, because I want to leave the possibility to support other types, such as XML.

**Comment by cciccia** [comment]
This change wouldnt affect that though right? Just makes the extensionless
request default to json?

That would make my life slightly easier if i would not have to put json on
the end of the url just cause of the way angular $resource deals with
putting ids in the url.

If not i can work around it

**Comment by ConnorJC3** [comment]
Yeah, it would only majorly screw http (But as an API we probably wouldn't be adding that), so if it makes the UI easier I can add it.

I'm going to see if there's a DRYer way to do it though, instead of needing to put the default on every route.

**Comment by ConnorJC3** [comment]
Ok, looks like using this in the ApplicationController will work across all routes and not clutter the routes file:

```ruby
before_action :set_default_request_format

def set_default_request_format
  request.format = :json unless params[:format]
end
```

I'm not sure if I can modify the commits on a pull request before merging.

**Comment by ConnorJC3** [comment]
Nevermind, I see you used a branch here, I can just push to that. Once I get a chance in about 2-3 hours  I'll clean up the test and defaults so I can merge it.

**Comment by ConnorJC3** [comment]
Fixed these issues in commits 9fe70b747ca43c723f9dc533ce85483340f83cc7, 36ef38a2c5c7b3c1e392488680a7fd612785620b, f01a867abbaa484b76ad514ec3bbae65ca98f680, and 98994b2b48d11bae01a15615845be0817a91d6fb on develop.

**Pull request closed without merging**
